### ISSUE TITLE
OS X GTK+ gui without X11

### ISSUE THREAD

**Issue by jhgorse** [jhgorse/onevideo#17]
How to reproduce: 
1) Remove X11 from OS X 10.11:
https://gist.github.com/TonyMtz/714e73ccb79e21c4fc9c
2) Build gdk-pixbuf, gtk+3, cairo, and pango --without-x (--without-x11).

What happens:
Gtk widgets cease working properly. For example,
(OneVideo:88935): Gtk-WARNING **: drawing failure for widget 'GtkBox': out of memory
and the widget with not draw.

**Comment by nirbheek** [comment]
I've always run the OneVideo GTK+ GUI without X11 on OS X, so this should definitely work (in theory). I've never even had X11 installed on my test OS X machine.

**Comment by jhgorse** [comment]
Apparently I will just have to abstain from using timeoverlay and one-video-gui simultaneously. This env variable "fix" to use timeoverlay element breaks gkt3 apps, including the demo apps.
PANGOCAIRO_BACKEND=fontconfig

http://gstreamer-bugs.narkive.com/Lq4DvEMW/bug-752147-new-glimagesink-and-textoverlay-aren-t-friends-on-os-x
